Repository fplbot/fplbot, pull requests merged in 2023-09, with the labels that each got.

#334 Remove threshold for posting changes to players to Slack
  src/FplBot.EventHandlers.Slack/Helpers/PlayerExtensions.cs
Labels: enhancement

#335 Improve handling of large notifications on Discord
  src/Fpl.Client/Models/Pick.cs
  src/FplBot.EventHandlers.Discord/GameweekStartedHandler.cs
  src/FplBot.Formatting/ClassicLeagueEntryExtensions.cs
  src/FplBot.Formatting/Formatter.cs
  src/FplBot.Formatting/TransfersByGameWeek.cs
  src/FplBot.WebApi/Endpoints/Test/DebugRoute.cs
  src/FplBot.WebApi/Endpoints/Test/Gameweekstart/TestGwStart.cs
  test.http
Labels: bug, enhancement

#337 Bugfix: Count own goals into score
  src/Fpl.EventPublishers/Models/Mappers/LiveEventsExtractor.cs
  src/FplBot.Tests/GetUpdatedFixtureEventsTests.cs
  src/FplBot.Tests/Helpers/TestBuilder.cs
Labels: bug

#338 Bugfix: multi taunts
  src/FplBot.Formatting/FixtureStats/Describers/RedCardDescriber.cs
  src/FplBot.Formatting/FixtureStats/TauntData.cs
  src/FplBot.Tests/Formatting/FixtureEventsFormattingTests.cs
Labels: bug

#339 Bugfix: Include zero percent ownership
  src/FplBot.EventHandlers.Discord/Helpers/PlayerExtensions.cs
  src/FplBot.EventHandlers.Slack/Helpers/PlayerExtensions.cs
Labels: bug
